on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/scrape-test.yml
  schedule:
    - cron: 0 0 1 * * # Once a month. Ref https://crontab.guru/examples.html
name: Scrape Test
jobs:
  scheduled:
    name: Scrape Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Build
        run: npm install # any dependencies you may need
      - name: Scrape
        run: npm run test # actually run your npm script for testing
        # env:
        #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
