on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/scrape-test.yml
  schedule:
    - cron: 0 0 1 * * # Once a month. Ref https://crontab.guru/examples.html
name: Scrape Test
jobs:
  scheduled:
    name: Scrape Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      # - name: Fetch group buy link page
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://geekhack.org/index.php?board=70.0
      #     downloaded_filename: ./tests/group-buy-links-test-page.html
      # - name: Fetch group buy page
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://geekhack.org/index.php?topic=113697.0
      #     downloaded_filename: ./tests/group-buy-test-page.html
      - name: Build
        run: npm install # any dependencies you may need
      - name: Run Test
        run: npm run test # actually run your npm script for testing
        # env:
        #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
